#!/usr/bin/env python
"""Generate mouse profiles reference documentation from JSON definitions.

This script reads mouse profile JSON files from MouseDefinitions/ and generates
RST documentation for the reference section.

Can be run standalone (no Slicer required):
    python MouseMaster/Testing/Python/test_generate_mouse_profiles.py

Output: docs/reference/_generated/mouse-profiles.rst
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path


def get_project_root() -> Path:
    """Get the project root directory."""
    # Handle both standalone execution and CI environments
    workspace = os.environ.get("GITHUB_WORKSPACE")
    if workspace:
        return Path(workspace)

    # From Testing/Python/, go up to MouseMaster/, then to project root
    return Path(__file__).parent.parent.parent.parent


def get_definitions_dir() -> Path:
    """Get the MouseDefinitions directory."""
    return get_project_root() / "MouseMaster" / "Resources" / "MouseDefinitions"


def get_output_dir() -> Path:
    """Get the output directory for generated documentation."""
    return get_project_root() / "docs" / "reference" / "_generated"


def load_mouse_definitions() -> list[dict]:
    """Load all mouse definition JSON files.

    Returns:
        List of mouse definition dictionaries, sorted by name
    """
    definitions_dir = get_definitions_dir()
    definitions = []

    for json_file in sorted(definitions_dir.glob("*.json")):
        with open(json_file) as f:
            data = json.load(f)
            data["_filename"] = json_file.name
            definitions.append(data)

    # Sort by name for consistent output
    return sorted(definitions, key=lambda d: d.get("name", ""))


def generate_button_table(buttons: list[dict]) -> list[str]:
    """Generate RST table for buttons.

    Args:
        buttons: List of button definitions

    Returns:
        List of RST lines for the table
    """
    lines = [
        ".. list-table::",
        "   :header-rows: 1",
        "   :widths: 15 20 15 15 35",
        "",
        "   * - ID",
        "     - Name",
        "     - Qt Button",
        "     - Remappable",
        "     - Default Action",
    ]

    for button in buttons:
        remappable = "Yes" if button.get("remappable", False) else "No"
        default_action = button.get("defaultAction", "-")
        if default_action != "-":
            default_action = f"``{default_action}``"

        lines.extend(
            [
                f"   * - ``{button['id']}``",
                f"     - {button['name']}",
                f"     - {button['qtButton']}",
                f"     - {remappable}",
                f"     - {default_action}",
            ]
        )

    return lines


def generate_features_list(features: dict) -> list[str]:
    """Generate RST list for features.

    Args:
        features: Features dictionary

    Returns:
        List of RST lines
    """
    lines = []
    feature_names = {
        "horizontalScroll": "Horizontal Scroll",
        "thumbWheel": "Thumb Wheel",
        "gestureButton": "Gesture Button",
    }

    for key, name in feature_names.items():
        if features.get(key, False):
            lines.append(f"- {name}")

    if not lines:
        lines.append("- None")

    return lines


def generate_mouse_profiles_rst(definitions: list[dict]) -> str:
    """Generate RST content for mouse profiles reference.

    Args:
        definitions: List of mouse definition dictionaries

    Returns:
        RST content as string
    """
    lines = [
        ".. This file is auto-generated by test_generate_mouse_profiles.py",
        ".. Do not edit manually",
        "",
    ]

    for defn in definitions:
        mouse_name = defn["name"]
        lines.append(mouse_name)
        lines.append("-" * len(mouse_name))
        lines.append("")

        # Basic info
        lines.append(f"**Vendor:** {defn['vendor']}")
        lines.append("")
        lines.append(f"**Vendor ID:** ``{defn['vendorId']}``")
        lines.append("")

        product_ids = defn.get("productIds", [])
        if product_ids:
            ids_str = ", ".join(f"``{pid}``" for pid in product_ids)
            lines.append(f"**Product IDs:** {ids_str}")
        else:
            lines.append("**Product IDs:** Any (generic profile)")
        lines.append("")

        # Profile ID
        lines.append(f"**Profile ID:** ``{defn['id']}``")
        lines.append("")

        # Buttons table
        lines.append("Buttons")
        lines.append("^^^^^^^")
        lines.append("")
        lines.extend(generate_button_table(defn.get("buttons", [])))
        lines.append("")

        # Features
        features = defn.get("features", {})
        lines.append("Features")
        lines.append("^^^^^^^^")
        lines.append("")
        lines.extend(generate_features_list(features))
        lines.append("")
        lines.append("")

    # Add note about custom profiles
    lines.extend(
        [
            "Creating Custom Profiles",
            "------------------------",
            "",
            "Don't see your mouse? You can create a custom profile:",
            "",
            "1. Use the **Button Detection Wizard** in MouseMaster to detect your mouse's button codes",
            "2. Save the detected profile for future use",
            "3. Consider contributing your profile to the project",
            "",
            "See :doc:`/developer-guide/adding-mouse-profiles` for details on creating",
            "and contributing mouse profiles.",
            "",
        ]
    )

    return "\n".join(lines)


def generate_mouse_profiles_reference() -> Path:
    """Generate the mouse profiles reference documentation.

    Returns:
        Path to the generated file
    """
    output_dir = get_output_dir()
    output_dir.mkdir(parents=True, exist_ok=True)

    definitions = load_mouse_definitions()
    rst_content = generate_mouse_profiles_rst(definitions)

    output_file = output_dir / "mouse-profiles.rst"
    with open(output_file, "w") as f:
        f.write(rst_content)

    print(f"Generated: {output_file}")
    print(f"Profiles documented: {len(definitions)}")

    return output_file


def test_generate_mouse_profiles():
    """Test that mouse profiles documentation can be generated."""
    output_file = generate_mouse_profiles_reference()
    assert output_file.exists(), f"Output file not created: {output_file}"

    content = output_file.read_text()
    assert "Logitech MX Master 3S" in content, "MX Master 3S not in output"
    assert "Generic 3-Button Mouse" in content, "Generic 3-Button not in output"
    assert ".. list-table::" in content, "Button table not in output"

    print("Test passed: mouse profiles documentation generated successfully")


if __name__ == "__main__":
    output_file = generate_mouse_profiles_reference()

    # Print some of the output for verification
    print("\n" + "=" * 60)
    print("Generated content preview:")
    print("=" * 60)
    content = output_file.read_text()
    # Print first 50 lines
    for line in content.split("\n")[:50]:
        print(line)
    print("...")

    sys.exit(0)
